import { chromium, expect } from '@playwright/test';
const base = process.env.BASE_URL || 'http://localhost:5174';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  // Exercise the offline fallback deterministically without relying on a tile provider.
  await page.route('https://tiles.stadiamaps.com/**', route => route.abort());
  await page.goto(base + '/login/admin');
  await page.getByRole('button', { name: 'Sign in as admin' }).click();
  await page.waitForURL('**/admin/connect');
  const map = page.locator('.alumni-leaflet-map');
  await expect(map).toBeVisible();
  await expect(page.locator('.map-local-geography').first()).toBeAttached();
  await expect(page.locator('.map-interaction-note')).toContainText('Showing local geography');
  await expect(page.locator('.leaflet-control-attribution')).toBeVisible();
  await page.locator('.geo-person').first().click();
  await expect(page.locator('.geo-profile')).toBeVisible();
  await expect(page.locator('.map-pin-active')).toBeVisible();
  const marker = page.locator('.map-pin-active');
  expect(await marker.evaluate(el => getComputedStyle(el).transform)).not.toBe('matrix(1, 0, 0, 1, 0, 0)');
  await page.getByRole('button', { name: 'Close alumni profile' }).click();
  await page.getByRole('button', { name: 'Recenter map', exact: true }).click();
  const cluster = page.locator('.alumni-cluster-light, .alumni-cluster-dark').first();
  await expect(cluster).toBeVisible();
  const pane = page.locator('.leaflet-map-pane');
  const before = await pane.getAttribute('style');
  const rect = await map.boundingBox();
  await page.mouse.move(rect.x + 90, rect.y + 180);
  await page.mouse.down();
  await page.mouse.move(rect.x + 170, rect.y + 240, { steps: 8 });
  await page.mouse.up();
  await expect.poll(() => pane.getAttribute('style')).not.toBe(before);
  await page.waitForTimeout(400);
  const zoomBefore = await page.locator('.leaflet-tile').first().getAttribute('src');
  await map.hover({ position: { x: 250, y: 300 } });
  await page.mouse.wheel(0, -400);
  await expect.poll(() => page.locator('.leaflet-tile').first().getAttribute('src')).not.toBe(zoomBefore);
  await expect(map).not.toHaveClass(/leaflet-zoom-anim/);
  await page.getByRole('button', { name: 'Recenter map', exact: true }).click();
  await expect(cluster).toBeVisible();
  await cluster.click();
  await expect(page.locator('.map-pin-idle').first()).toBeVisible();
  await page.locator('.map-pin-idle').first().click();
  await expect(page.locator('.geo-profile')).toBeVisible();
  await page.getByRole('button', { name: 'Voice call', exact: true }).click();
  await expect(page.locator('.call-status.connected')).toBeVisible();
  await page.getByRole('button', { name: 'End call', exact: true }).click();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.screenshot({ path: '/tmp/pantiss-map.png' });
  await page.goto(base + '/admin');
  await page.waitForURL('**/admin/connect');
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await page.waitForURL('**/admin/overview');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + '/admin/connect');
  await expect(map).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: '/tmp/pantiss-map-mobile.png' });
  if (errors.length) throw Error(errors.join('\n'));
  console.log('PASS: admin routes, local geography, attribution, selection, panning, zoom, clusters, calls, mobile layout, no runtime errors.');
} catch (error) { await page.screenshot({ path: '/tmp/map-failure.png' }); throw error; } finally { await browser.close(); }
