import { chromium } from '@playwright/test';
const base=process.env.BASE_URL||'http://localhost:5174';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/login/admin');
await page.getByRole('button',{name:'Sign in as admin'}).click();
await page.waitForURL('**/admin/connect');
await page.locator('.fallback-map').waitFor();
await page.locator('.geo-person').first().click();
await page.locator('.geo-profile').waitFor();
if(!await page.locator('.map-marker.selected').count())throw Error('Selected marker missing');
await page.getByRole('button',{name:'Close alumni profile'}).click();
await page.getByRole('button',{name:'Recenter map',exact:true}).click();
const map=page.locator('.fallback-map');const rect=await map.boundingBox();
const before=await page.locator('.map-transform').getAttribute('transform');
await page.mouse.move(rect.x+100,rect.y+200);await page.mouse.down();await page.mouse.move(rect.x+175,rect.y+250,{steps:8});await page.mouse.up();
const after=await page.locator('.map-transform').getAttribute('transform');
if(before===after)throw Error('Map did not pan');
await page.mouse.wheel(0,-400);await page.waitForTimeout(200);
const zoom=await page.locator('.map-transform').getAttribute('transform');if(after===zoom)throw Error('Map did not zoom');
await page.getByRole('button',{name:'Recenter map',exact:true}).click();
await page.locator('.map-cluster').first().click();await page.locator('.geo-profile').waitFor();
await page.getByRole('button',{name:'Voice call',exact:true}).click();
await page.waitForTimeout(2800);if(!await page.locator('.call-status.connected').count())throw Error('Call not connected');
await page.getByRole('button',{name:'End call',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();
await page.screenshot({path:'/tmp/pantiss-map.png'});
await page.goto(base+'/admin');await page.waitForURL('**/admin/connect');
await page.getByRole('link',{name:'Overview',exact:true}).click();await page.waitForURL('**/admin/overview');
await page.setViewportSize({width:390,height:844});await page.goto(base+'/admin/connect');await page.locator('.fallback-map').waitFor();
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile horizontal overflow');
await page.screenshot({path:'/tmp/pantiss-map-mobile.png'});
await page.goto(base+'/');await page.locator('.hero').waitFor();await page.screenshot({path:'/tmp/pantiss-landing-mobile.png'});
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: admin default route, overview, list/marker selection, drag pan, wheel zoom, clusters, simulated call, mobile layout, no runtime errors.');
await browser.close();
