import { useEffect, useRef } from 'react';
import { X, Search, ArrowUpRight, CheckCircle2, Inbox, Loader2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApp } from '../../context/AppContext';
export function Logo({dark=false}){return <Link to="/" className={`brand ${dark?'brand-light':''}`} aria-label="Pantiss Alumni Network home"><span className="brand-mark">P<span/></span><span className="brand-word">PANTISS<small>ALUMNI NETWORK</small></span></Link>}
export function Button({children,variant='primary',className='',...props}){return <button className={`button ${variant} ${className}`} {...props}>{children}</button>}
export function Avatar({person,size='md'}){return <span className={`avatar ${size}`}><img src={person.photo} alt={person.name} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/><span className="avatar-initial">{person.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span>{person.online&&<i className="online-dot"/>}</span>}
export function Badge({children,color='neutral'}){return <span className={`badge ${color}`}>{children}</span>}
export function SearchBar({value,onChange,placeholder='Search...',className=''}){return <label className={`search-field ${className}`}><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}><X size={14}/></button>}</label>}
export function Select({label,value,onChange,options}){return <label className="select-field"><span className="sr-only">{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">{label}</option>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></label>}
export function PageHeading({eyebrow,title,description,children}){return <div className="page-heading"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="heading-actions">{children}</div></div>}
export function EmptyState({title='Nothing here yet',description='Try a different search or adjust your filters.',children}){return <div className="empty-state"><Inbox size={32}/><h3>{title}</h3><p>{description}</p>{children}</div>}
export function Modal({title,children,onClose,wide=false}){const ref=useRef(null);useEffect(()=>{const old=document.activeElement;const bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const handle=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll('button,input,select,textarea,a[href],[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=bodyOverflow;document.removeEventListener('keydown',handle);old?.focus()}},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide?'wide':''}`}><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</section></div>}
export function Toast(){const {toast}=useApp();return toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast.message}</div>}
export function SectionTitle({title,to,link='View all'}){return <div className="section-title"><h2>{title}</h2>{to&&<Link to={to}>{link}<ArrowUpRight size={16}/></Link>}</div>}
export function Loading(){return <div className="loading"><Loader2 className="spin" size={26}/><span>Getting your network ready…</span></div>}
